---
T_transform:
    rows: 4
    cols: 4
    dt: d
    data: [0.994349, -0.000142885, -0.000317681, -32.421, 0.000175802, 0.994349, 0.106158, -1.18249, 0.000300718, -0.106158, 0.994349, 2.17339, 0.0, 
              0.0, 0.0, 1.0]

RGB_INTRINSICS:
    K_rgb:
        rows: 3
        cols: 3
        dt: d
        data: [1127.26, 0.0, 953.136, 0.0, 1126.26, 545.698, 0.0, 0.0, 1.0]

    fx: 1127.26
    fy: 1126.26
    cx: 953.136
    cy: 545.698

DEPTH_INTRINSICS:
    K_depth:
        rows: 3
        cols: 3
        dt: d
        data: [504.867, 0.0, 333.731, 0.0, 504.958, 339.597, 0.0, 0.0, 1.0]

    fx: 504.867
    fy: 504.958
    cx: 333.731
    cy: 339.597
